ALTER TABLE PRODUTOS DROP Codigo_fornecedor_FK;
DROP TABLE IF EXISTS PRODUTOS;
DROP TABLE IF EXISTS FORNECEDORES;

CREATE TABLE FORNECEDORES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CNPJ VARCHAR(20) NOT NULL,
    Nome_juridico VARCHAR(100) NOT NULL,
    Marca VARCHAR(50) NOT NULL,
    Endereco VARCHAR2(255) NOT NULL,
    Telefone VARCHAR2(255) NOT NULL,
    Email VARCHAR2(255) NOT NULL,
    UNIQUE (CNPJ)
);

CREATE TABLE PRODUTOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Tipo VARCHAR(50) NOT NULL,
    Quantidade INT NOT NULL,
    Fornecedor_id INT,
    FOREIGN KEY (Fornecedor_id) REFERENCES FORNECEDORES(id) ON DELETE CASCADE
);

ALTER TABLE PRODUTOS add constraint Fornecedor_id_FK (Fornecedor_id) refeences FORNECEDORES (id)